# Generated by Django 2.2.17 on 2021-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210310_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_inspector',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
