# Generated by Django 2.2.19 on 2021-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210312_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Administrator / Custodian'), ('inspector', 'Inspectors'), ('simple_user', 'Simple User')], default='simple_user', max_length=15),
        ),
    ]
