# Generated by Django 2.2.19 on 2021-03-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
    ]
