# Generated by Django 2.2.19 on 2021-03-28 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0002_auto_20210328_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
