# Generated by Django 2.2.19 on 2021-03-28 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('district_services', '0003_auto_20210328_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('image', models.ImageField(upload_to='district_logos', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inspectors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'School Buildings',
                'ordering': ('created',),
            },
        ),
    ]
