# Generated by Django 2.2.19 on 2021-03-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('district_services', '0005_schoolbuilding_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins_against_district', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolbuilding',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools_in_district', to='district_services.District'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Section Name')),
                ('paper_towel_dispensers', models.PositiveIntegerField(default=0)),
                ('toiler_tissue_dispensers', models.PositiveIntegerField(default=0)),
                ('hand_soap_dispensers', models.PositiveIntegerField(default=0)),
                ('hand_sanitizer_dispensers', models.PositiveIntegerField(default=0)),
                ('estimated_time_to_clean', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cleaner', models.ForeignKey(blank=True, limit_choices_to={'role': 'simple_user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_cleaner', to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(blank=True, related_name='people_in_section', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Room Name')),
                ('square_feet', models.PositiveIntegerField(default=0)),
                ('desks', models.PositiveIntegerField(default=0)),
                ('windows', models.PositiveIntegerField(default=0)),
                ('trash_cans', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cleaners', models.ManyToManyField(blank=True, related_name='cleaners_of_room', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='district_services.RoomType')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_in_section', to='district_services.Section')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ('created',),
            },
        ),
    ]
