# Generated by Django 2.2.19 on 2021-03-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0007_auto_20210328_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('-created',), 'verbose_name_plural': '1- Districts'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created',), 'verbose_name_plural': '5- Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ('-created',), 'verbose_name_plural': '4- Room Types'},
        ),
        migrations.AlterModelOptions(
            name='schoolbuilding',
            options={'ordering': ('-created',), 'verbose_name_plural': '2- School Buildings'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('-created',), 'verbose_name_plural': '3- Sections'},
        ),
    ]
