# Generated by Django 2.2.19 on 2021-03-29 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0009_auto_20210329_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cleaner',
        ),
        migrations.AlterField(
            model_name='room',
            name='cleaner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'simple_user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner_of_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
