# Generated by Django 2.2.19 on 2021-03-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0011_section_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='estimated_time_to_clean',
        ),
        migrations.AddField(
            model_name='room',
            name='estimated_time_to_clean',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
