# Generated by Django 2.2.19 on 2021-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0012_auto_20210329_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='estimated_time_to_clean',
            field=models.IntegerField(default=0),
        ),
    ]
