# Generated by Django 2.2.19 on 2021-03-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0013_auto_20210330_1521'),
    ]

    operations = [

    ]
