# Generated by Django 2.2.19 on 2021-04-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0014_auto_20210331_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_equipments', to='district_services.Section')),
            ],
            options={
                'verbose_name_plural': '6- Equipments',
                'ordering': ('-created',),
            },
        ),
    ]
