# Generated by Django 2.2.19 on 2021-04-08 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('district_services', '0015_auto_20210407_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_employee', to='district_services.District')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_in_district', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1- Districts',
                'ordering': ('-created',),
            },
        ),
    ]
