# Generated by Django 2.2.19 on 2021-04-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0015_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '1- Product Type',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_equipments', to='district_services.Section'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='district_services.ToolType'),
        ),
    ]
