# Generated by Django 2.2.19 on 2021-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0016_auto_20210405_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
