# Generated by Django 2.2.19 on 2021-04-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0017_equipment_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('-created',), 'verbose_name_plural': '7- Equipments'},
        ),
        migrations.AlterModelOptions(
            name='tooltype',
            options={'ordering': ('-created',), 'verbose_name_plural': '6- Tool Type for Equipments'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_type_equipments', to='district_services.ToolType'),
        ),
        migrations.CreateModel(
            name='EquipmentNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost_per_unit', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_equipments_needed', to='district_services.Section')),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_type_equipments_needed', to='district_services.ToolType')),
            ],
            options={
                'verbose_name_plural': '8- Equipment Needed by section.',
                'ordering': ('-created',),
            },
        ),
    ]
