# Generated by Django 2.2.19 on 2021-04-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0018_auto_20210405_1039'),
        ('district_services', '0016_employeeindistrict'),
    ]

    operations = [
    ]
