# Generated by Django 2.2.19 on 2021-04-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0019_merge_20210409_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeindistrict',
            options={'ordering': ('-created',), 'verbose_name_plural': '6- Employees With District Code'},
        ),
    ]
