# Generated by Django 2.2.19 on 2021-04-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0020_auto_20210412_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='hand_sanitizer_dispensers',
        ),
        migrations.RemoveField(
            model_name='section',
            name='hand_soap_dispensers',
        ),
        migrations.RemoveField(
            model_name='section',
            name='paper_towel_dispensers',
        ),
        migrations.RemoveField(
            model_name='section',
            name='toiler_tissue_dispensers',
        ),
    ]
