# Generated by Django 2.2.19 on 2021-04-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0021_auto_20210412_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('-created',), 'verbose_name_plural': '7- Registered Equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipmentneeded',
            options={'ordering': ('-created',), 'verbose_name_plural': '9- Equipment Needed by section.'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='size',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='updated',
        ),
        migrations.AddField(
            model_name='equipment',
            name='title',
            field=models.CharField(default='some', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EquipmentInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unit to represent with size')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_in_section', to='district_services.Equipment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_equipments', to='district_services.Section')),
            ],
            options={
                'verbose_name_plural': '8- Equipments in Sections',
                'ordering': ('-created',),
            },
        ),
    ]
