# Generated by Django 2.2.19 on 2021-04-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0022_auto_20210421_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentneeded',
            name='tool_type',
        ),
        migrations.AddField(
            model_name='equipmentneeded',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_needed', to='district_services.Equipment'),
            preserve_default=True,
        ),
    ]
