# Generated by Django 2.2.19 on 2021-04-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0023_auto_20210421_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentInSection',
            new_name='EquipmentInSchoolBuilding',
        ),
        migrations.RemoveField(
            model_name='equipmentinschoolbuilding',
            name='section',
        ),
        migrations.AddField(
            model_name='equipmentinschoolbuilding',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_equipments', to='district_services.SchoolBuilding'),
            preserve_default=True,
        ),
    ]
