# Generated by Django 2.2.19 on 2021-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0026_auto_20210421_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentneeded',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmentneeded',
            name='title',
            field=models.CharField(default='some', max_length=255),
            preserve_default=False,
        ),
    ]
