# Generated by Django 2.2.19 on 2021-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0027_auto_20210421_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='tool_type',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.AddField(
            model_name='room',
            name='tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='estimated_time_to_clean',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ToolType',
        ),
    ]
