# Generated by Django 2.2.19 on 2021-04-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0029_auto_20210422_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='flushable',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
