# Generated by Django 2.2.19 on 2021-04-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0030_room_flushable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='clean_up_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='preparation_time',
        ),
    ]
