# Generated by Django 2.2.19 on 2021-05-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0032_auto_20210504_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinschoolbuilding',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentinschoolbuilding',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipmentinschoolbuilding',
            name='size',
        ),
    ]
