# Generated by Django 2.2.19 on 2021-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_no',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
