# Generated by Django 2.2.19 on 2021-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20210330_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ('-created',), 'verbose_name_plural': '3- Inspections'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-created',), 'verbose_name_plural': '4- Inspection Parameters'},
        ),
        migrations.AlterModelOptions(
            name='parameterimage',
            options={'ordering': ('-created',), 'verbose_name_plural': '5- Parameter Images'},
        ),
        migrations.AlterModelOptions(
            name='productneeded',
            options={'ordering': ('-created',), 'verbose_name_plural': '2- Product Needed'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('-created',), 'verbose_name_plural': '1- Product Type'},
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
