# Generated by Django 2.2.19 on 2021-04-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_auto_20210331_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductNeeded',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
