# Generated by Django 2.2.19 on 2021-04-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0014_auto_20210331_0733'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productneeded',
            options={'ordering': ('-created',), 'verbose_name_plural': '3- Product Needed'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductType')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district_services.Section')),
            ],
            options={
                'verbose_name_plural': '2- Products In Stock',
                'ordering': ('-created',),
            },
        ),
    ]
