# Generated by Django 2.2.19 on 2021-04-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_services', '0018_auto_20210405_1039'),
        ('products', '0003_remove_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='products.Product')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_used_in_section', to='district_services.Section')),
            ],
            options={
                'verbose_name_plural': '3- Product Needed',
                'ordering': ('-created',),
            },
        ),
    ]
