# Generated by Django 2.2.19 on 2021-04-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210412_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productneeded',
            options={'ordering': ('-created',), 'verbose_name_plural': '4- Product Needed'},
        ),
        migrations.AlterModelOptions(
            name='productused',
            options={'ordering': ('-created',), 'verbose_name_plural': '5- Product Needed'},
        ),
        migrations.AlterModelOptions(
            name='registeredproduct',
            options={'ordering': ('-created',), 'verbose_name_plural': '2- Register Products'},
        ),
        migrations.AlterModelOptions(
            name='sectionproduct',
            options={'ordering': ('-created',), 'verbose_name_plural': '3- Products In Section'},
        ),
        migrations.AlterField(
            model_name='sectionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_products', to='products.RegisteredProduct'),
        ),
        migrations.AlterField(
            model_name='sectionproduct',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_section', to='district_services.Section'),
        ),
    ]
